# Generated by Django 5.1.1 on 2024-11-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_contact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='meassage',
            new_name='message',
        ),
    ]
